version: "3.5"

services:
  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: postgres

  product:
    image: loja/produtos
    ports:
      - "8081:8081"
    environment:
      POSTGRES_URL: jdbc:postgresql://postgres:5432/postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    depends_on:
      - postgres

  user:
    image: loja/usuario
    ports:
      - "8080:8080"
    environment:
      POSTGRES_URL: jdbc:postgresql://postgres:5432/postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    depends_on:
      - postgres

  shopping:
    image: loja/shop
    ports:
      - "8082:8082"
    environment:
      POSTGRES_URL: jdbc:postgresql://postgres:5432/postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PRODUCT_API_URL: http://product:8081
      USER_API_URL: http://user:8080
    depends_on:
      - postgres

  gateway:
    image: loja/gateway
    ports:
      - "8084:8084"
    environment:
      PRODUCT_API_URL: http://product:8081
      USER_API_URL: http://user:8080
      SHOPPING_API_URL: http://shopping:8082
    depends_on:
      - postgres
